### ISSUE TITLE
Loosing exif data

### ISSUE THREAD

**Issue by surcoufx83** [benmajor/PHP-Image-Resize#2]
Hello,

i like using your library very much, it is good and easy to implement. I noticed that I lose the exif data of the images when resizeCrop is used. This causes Chrome to display pictures taken from the cell phone not rotated correctly. 
Additionally the images look slightly grey, they are not as color intensive as the original. 

In my application only resizeCrop and output are used.

Best regards, Stefan
![518645e112](https://user-images.githubusercontent.com/1303974/99843041-2f4ff480-2b71-11eb-8ec0-6d9d9f9b2f57.jpg)
![518645e112-700x560](https://user-images.githubusercontent.com/1303974/99843051-324ae500-2b71-11eb-98f4-e1a11e623986.jpg)

**Comment by surcoufx83** [comment]
With this images you can see the loss of colors a little bit better

![0c22687816](https://user-images.githubusercontent.com/1303974/99843731-4d6a2480-2b72-11eb-81a0-8969600af30f.jpeg)
![0c22687816-700x560](https://user-images.githubusercontent.com/1303974/99843738-4f33e800-2b72-11eb-8b25-a8170f6a16e2.jpg)

**Comment by benmajor** [comment]
Thanks for using the lib and glad you find it useful!

Regarding the EXIF data, sadly it falls outside the scope of the library as EXIF data is very troublesome to work with. This is in part due to the shortcomings of the GD library (you can read more about it in the answers over on StackOverflow: https://stackoverflow.com/questions/10182890/copy-an-image-and-preserve-its-exif-iptc-data-with-php-imagecreatefromjpeg).

Regarding the colour loss, again sadly this is down to GD's limitations, which resamples to a specific color profile. At a guess, I would suggest that the images are using Adobe RGB, while GD operates in sRGB. The only option really is to move Imagick, which is far less supported.
